# Generated by Django 4.1.3 on 2023-02-18 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_carts_staus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='user',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='Products',
            new_name='products',
        ),
        migrations.RenameField(
            model_name='reviews',
            old_name='comments',
            new_name='comment',
        ),
        migrations.AlterField(
            model_name='orders',
            name='staus',
            field=models.CharField(choices=[('order-placed', 'order-placed'), ('despathed', 'depatched'), ('in-transit', 'in-transit'), ('cancelled', 'cancelled')], default='in-cart', max_length=200),
        ),
    ]
