# Generated by Django 4.1.3 on 2023-02-23 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_staus_orders_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carts',
            old_name='staus',
            new_name='status',
        ),
    ]
